### ISSUE TITLE
One background color all across

### ISSUE THREAD

**Issue by gj1118** [saadq/Material-Spacegray#2]
Can you make the background color one and the same ? You might have to create a new color scheme ..

![image](https://cloud.githubusercontent.com/assets/473101/9087830/0fe11cfc-3b5b-11e5-86a4-77fe0fa9b5bc.png)

**Comment by saadq** [comment]
What color scheme are you using? And what file type is this? If you use the base16-ocean color scheme that I shipped with this theme, there shouldn't be any color variation.

**Comment by gj1118** [comment]
I was using the material-theme color scheme. That was my folly. Sorry about that. I just changed to Base16 and I can still see there is a color difference. The file type is python. 


here are my settings 
```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": false,
	"color_scheme": "Packages/Material Spacegray/schemes/base16-ocean.tmTheme",
	"font_face": "Consolas",
	"font_options":
	[
		"subpixel_antialias"
	],
	"font_size": 11,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Laravel Blade Highlighter",
		"BracketHighlighter",
		"SublimeLinter-pylint",
		"Vintage"
	],
	"line_padding_bottom": 4,
	"line_padding_top": 4,
	"material_spacegray_small_tab": true,
	"material_theme_bold_tab": false,
	"overlay_scroll_bars": "enabled",
	"tabs_padding_medium": true,
	"tabs_small": true,
	"theme": "Material Spacegray.sublime-theme"
}
```
![image](https://cloud.githubusercontent.com/assets/473101/9088859/416d0a60-3b60-11e5-95ee-d9f726a47e4e.png)

**Comment by saadq** [comment]
I don't see any color variation in that screenshot you just posted. Are you saying you want the background color of the editor to be the same as the sidebar color?

**Comment by gj1118** [comment]
Yes that is what I was trying to imply.

---------------------------
With Regards
Gagan Janjua

**Comment by saadq** [comment]
I've made some major updates to the repo. There will be two themes now, Material Spacegray and Material Spacegray Darker. There will be color schemes that match both of them, and you can mix them if you would prefer contrast. You can check out the screenshots, I believe this gives you what you want. It should update on Package Control within an hour.

**Comment by gj1118** [comment]
That should be it... :) thanks

**Comment by saadq** [comment]
Package Control can take about an hour to update, so you may have to wait until then, unless you'd rather just manually download the ZIP from the repo.
