### ISSUE TITLE
Darker background

### ISSUE THREAD

**Issue by gj1118** [saadq/Material-Spacegray#3]
Hi, I just upgraded to the latest version . However I see that the inputs have a darker background. Here is a snapshot. 

![image](https://cloud.githubusercontent.com/assets/473101/9091793/2349b73a-3b70-11e5-89bd-fca5c97c1d43.png)

Also note that the background is not uniform.While there is no padding on the left hand side, there seems to be some padding on the top and bottom. 

Even the snapshots you posted in the readme have this issue. 

Can the darker background be removed ?  

Thanks

**Comment by saadq** [comment]
Just fixed this, and pushed the changes to Package Control. It should update automatically for you under an hour, or you can manually download the latest version. Everything should look perfect now, fingers crossed.
