### ISSUE TITLE
JS icon is jagged

### ISSUE THREAD

**Issue by gj1118** [saadq/Material-Spacegray#4]
Hi, 
I have experienced with this theme that the JS icon is jagged .. while the material theme comes with a smooth JS icon .. 

Material theme darker JS icon 

![image](https://cloud.githubusercontent.com/assets/473101/9094108/108ee36e-3b7e-11e5-8e96-71d024e916f9.png)

Material Spacegray theme JS Icon 
![image](https://cloud.githubusercontent.com/assets/473101/9094133/299d05b6-3b7e-11e5-9566-80f909ff6910.png)

**Comment by saadq** [comment]
I keep failing you gj1118 :(

Fixed the icon, you can wait an hour or less, or just download the latest version. Thanks for raising the issue.

**Comment by gj1118** [comment]
I am sorry for being a pain ..  :(

**Comment by saadq** [comment]
Not at all! The theme is getting a lot better due to the issues you've raised :)
