### ISSUE TITLE
Doesn't show the input area for some plugins

### ISSUE THREAD

**Issue by kumarharsh** [saadq/Material-Spacegray#6]
Hi,

I'm using Emmet, AdvancedNewFile, etc, which open their own inputs near the status bar, like to create a new file via ANF, pressing <kbd>Win + Alt + N</kbd> or to wrap a peice of HTML in another tag via EMMET, pressing <kbd>Ctrl + Shift + G</kbd>.

These open up an input area down below near the status bar (just like Sublime's built-in Ctrl+I or Ctrl+F do for searches)

This theme doesn't show anything. just a fat block of that spacegray-blue chrome colour. There is no indication that an input is opened, and when any text is typed, nothing shows up.

See these screenshots for reference:

Material Spacegray
![Material Spacegray](https://cloud.githubusercontent.com/assets/760112/9105777/7f951e76-3c38-11e5-8bfd-98c844029b0a.png)

Material Spacegray with input (bad)
![Material Spacegray with input (bad)](https://cloud.githubusercontent.com/assets/760112/9105778/7f952a2e-3c38-11e5-8bdd-7c8e7f7dda3b.png)

Compare that with Sublime's default theme:
Default theme with input (good):
![Default theme with input (good)](https://cloud.githubusercontent.com/assets/760112/9105780/7f968d38-3c38-11e5-8cbf-3f83bdee8813.png)

**Comment by saadq** [comment]
Thanks Kumar, I'll look into it.

**Comment by saadq** [comment]
Hi Kumar,

Did you restart Sublime when you switched themes? I am not getting the same issue that you are. 

This is what happens when I use AdvancedNewFile with the theme: 

![input](https://cloud.githubusercontent.com/assets/5678694/9115852/350c3cee-3c2f-11e5-80c5-c3fd0744208d.PNG)

**Comment by kumarharsh** [comment]
@saadq yes, i've restarted sublime multiple times... nothing of note seems to be there in the console either.

**Comment by gj1118** [comment]
did you see this : https://cloud.githubusercontent.com/assets/474329/8178894/a0dd09c0-1412-11e5-8ecf-f7f9ade439ae.gif

**Comment by kumarharsh** [comment]
@gj1118 thanks for that... Earlier from the gif it's not apparent what's that going to do... the user is just resizing the pane...

I realize now that perhaps an Autosize is not being triggered by the theme in Sublime (it's a wontfix from the material-theme's creator [See #67](https://github.com/equinusocio/material-theme/issues/67))

So, we have to manually resize the bottom sidebar input area to trigger the recalculation, which shows the input.

**Comment by saadq** [comment]
@kumarharsh, did resizing the input area fix your issue?

**Comment by kumarharsh** [comment]
yes it did actually.
